;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="GameplayAbility.Player.Melee.SabreAttack01",NewTagName="GameplayAbility.Player.Melee.SpearAttack.Weak")
+GameplayTagRedirects=(OldTagName="GameplayCue.ShootProjectile.MagicBurst",NewTagName="GameplayCue.ProjectileSpawn.MagicBurst")
+GameplayTagRedirects=(OldTagName="GameplayCue.ShootProjectile",NewTagName="GameplayCue.ProjectileSpawn")
+GameplayTagRedirects=(OldTagName="GameplayAbility.Activate",NewTagName="GameplayAbility.Active")
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Heal",DevComment="")
+GameplayTagList=(Tag="Effects.HitReaction",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Event.Activate.Dash",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.End",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.Input",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.Start",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.End",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Start",DevComment="")
+GameplayTagList=(Tag="Event.ShootProjectile",DevComment="")
+GameplayTagList=(Tag="Event.Weapon.Equip",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Death",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.EquipWeapon",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.HitReaction",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.HitReaction.Enemy",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.HitReaction.Player",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Player.Melee.SpearAttack.Combo",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Player.Melee.SpearAttack.Heavy",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Player.Melee.SpearAttack.Weak",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Player.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Player.ShootProjectile",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Heal.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileImpact.MagicBurst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileSpawn.MagicBurst",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Regen",DevComment="")
+GameplayTagList=(Tag="Weapon.Magic.Staff",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.Spear",DevComment="")
+GameplayTagList=(Tag="Weapon.Ranged.Gun",DevComment="")

